version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '13306:3306'
    expose:
      # Opens port 3306 on the container
      - '13306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  user_image_fastapi:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
# Names our volume
volumes:
  my-db:
